#include <algorithm>
#include <array>
#include <iterator>
#include <random>
#include <chrono>
#include <cstddef>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <curses.h>
#include <iostream>
#include <string>
#include <vector>

#include "../dsp/Distortions/waveshape/Waveshapes.h"

// the order the plugin plays. generated by --header, so the first build won't have it yet
#if __has_include("../dsp/Distortions/waveshape/WaveshapeOrder.h")
#include "../dsp/Distortions/waveshape/WaveshapeOrder.h"
#define HAVE_ORDER_HEADER 1
#endif

// the XY pad's map. generated by analysis/umap_shapes.py --header, after harmonic_features
#if __has_include("../dsp/Distortions/waveshape/WaveshapeMap.h")
#include "../dsp/Distortions/waveshape/WaveshapeMap.h"
#define HAVE_MAP_HEADER 1
#endif

using namespace waveshapes;

int seconds = 1;
float baseFreq = 40.0f;
float sampleRate = 44100.0f;

// ordering: 0 = pure curve similarity, higher = closer to the spectral flatness order. 32 with outlier relocation
// also paying it follows flatness at rank correlation 0.94..0.98 with no quarter-group flatness jumps, while
// neighbours still look alike; 128 is effectively a plain flatness sort
double flatnessWeight = 32.0;
// how much the slope of a curve counts next to its values when comparing shapes. 0 = values only
double slopeWeight = 1.0;
// shapes whose curve distance to both neighbours sums above median + this many robust stddevs get pulled out
// and re-inserted wherever they fit the curves around them best. 0 disables
double outlierSigma = 2.0;
// curves are peak normalised to 1 on a coarse grid. none may go past this anywhere in its input range
const double maxPeak = 1.5;


template <typename T>
T sinewave(T in, T freq) {
    return sin((2.0 * M_PI) * in * freq / (T)sampleRate);
}

template <typename T>
T cosinewave(T in, T freq) {
    return cos((2.0 * M_PI) * in * freq / (T)sampleRate);
}


struct HarmonicResults {
    double spectralFlatness;
    double oddness; // odd vs even harmonics after fundamental
    double nsPerSample; // time to shape one sample, filled in by main
};

HarmonicResults harmonicAnalyse(std::vector<double> &in, double* harmonicMags, int numSamples, int harmonics) {
    for (int harmonic = 1; harmonic <= harmonics; harmonic++) {
        double sinPart = 0.0f;
        double cosPart = 0.0f;

        for (int i = 0; i < numSamples; i++) {
            sinPart += in[i] * sinewave((float)i, baseFreq * (float)harmonic);
            cosPart += in[i] * cosinewave((float)i, baseFreq * (float)harmonic);
        }

        harmonicMags[harmonic - 1] = sqrtf(sinPart * sinPart + cosPart * cosPart) / (2.0 * sampleRate);
    }

    double oddSum = 0.0f;
    double evenSum = 0.0f;
    for (int harmonic = 1; harmonic < harmonics; harmonic++) {
        double* sum = harmonic % 2 == 0 ? &evenSum : &oddSum;

        *sum += 2.0 * harmonicMags[harmonic] / harmonics;
    }

    double geoMeanSum = 0.0f;
    double arithmeticMean = 0.0f;
    for (int harmonic = 0; harmonic < harmonics; harmonic++) {
        // epsilon so an empty bin (or silent output) doesn't produce -inf / NaN and break sorting
        double mag = harmonicMags[harmonic] + 1e-12;
        geoMeanSum += log(mag);
        arithmeticMean += mag / (float)harmonics;
    }

    return {
        exp(geoMeanSum / harmonics) / arithmeticMean,
        (evenSum) / (oddSum + evenSum)
    };
}



// ascii plot of each shape over x, y in [-1, 1]. left/right switch, q quits.
using Result = std::pair<Shape, HarmonicResults>;

int tui(const std::vector<std::vector<Result>>& groups) {
    initscr();
    cbreak();
    noecho();
    keypad(stdscr, TRUE);
    curs_set(0);

    int group = 0, idx = 0;
    double range = 1.0; // visible half-width of both axes, up/down zooms

    for (;;) {
        auto& sorted = groups[group];
        const int count = (int)sorted.size();

        erase();
        int h, w;
        getmaxyx(stdscr, h, w);

        // plot area: row 0 is the title, rest is the plane
        const int top = 1, rows = h - 1, cols = w;
        if (rows >= 3 && cols >= 3) {
            int cy = top + (rows - 1) / 2, cx = (cols - 1) / 2;
            mvhline(cy, 0, '-', cols);
            mvvline(top, cx, '|', rows);
            mvaddch(cy, cx, '+');
            char label[16];
            snprintf(label, sizeof label, "%g", range);
            mvaddstr(top, cx + 1, label);
            mvaddstr(cy + 1, cols - (int)strlen(label), label);
            snprintf(label, sizeof label, "%g", -range);
            mvaddstr(top + rows - 1, cx + 1, label);
            mvaddstr(cy + 1, 0, label);

            int prevRow = -1;
            for (int c = 0; c < cols; c++) {
                double x = range * (-1.0 + 2.0 * c / (cols - 1));
                double y = sorted[idx].first(x) / range;

                // shapes are only checked finite on [-1, 1], zooming out can go past that
                if (!std::isfinite(y)) { prevRow = -1; continue; }

                char mark = '*';
                if (y > 1.0) { y = 1.0; mark = '^'; }
                if (y < -1.0) { y = -1.0; mark = 'v'; }

                int row = top + (int)std::lround((1.0 - y) * 0.5 * (rows - 1));

                // connect steep jumps so folds and clips read as lines
                if (prevRow >= 0) {
                    int lo = std::min(prevRow, row), hi = std::max(prevRow, row);
                    for (int r = lo + 1; r < hi; r++) mvaddch(r, c, '.');
                }
                mvaddch(row, c, mark);
                prevRow = row;
            }
        }

        attron(A_REVERSE);
        mvprintw(0, 0, " %s [%d/%d] %s  flatness %.3e  oddness %.4f ", groupNames[group], idx + 1, count,
                 sorted[idx].first.name, sorted[idx].second.spectralFlatness, sorted[idx].second.oddness);
        attroff(A_REVERSE);
        printw("  zoom %gx  <- -> shape, , . group, up/down zoom, q quit", 1.0 / range);
        refresh();

        int ch = getch();
        if (ch == 'q' || ch == 'Q') break;
        if (ch == KEY_LEFT) idx = (idx + count - 1) % count;
        if (ch == KEY_RIGHT) idx = (idx + 1) % count;
        if (ch == ',') { group = (group + GroupCount - 1) % GroupCount; idx = 0; }
        if (ch == '.') { group = (group + 1) % GroupCount; idx = 0; }
        if (ch == KEY_UP) range = std::max(range * 0.5, 1.0 / 64.0);
        if (ch == KEY_DOWN) range = std::min(range * 2.0, 8.0);
    }

    endwin();
    return 0;
}

// orders one group by raw curve similarity. stderr gets the path stats and the step between neighbours
std::vector<Result> similarityOrder(std::vector<Result> results, const char* label, bool log) {
    std::sort(results.begin(), results.end(), [](auto& a, auto& b) {
        return a.second.spectralFlatness < b.second.spectralFlatness;
    });

    // path from the least to the most spectrally flat shape in the group
    // that visits every shape once and minimises the curve distance between neighbours
    const int n = (int)results.size();
    if (n < 3) return results;
    const int points = 512;

    // curve distance = squared difference of the values + slopeWeight * squared difference of the slopes.
    // slopes go through atan first so one near-vertical jump can't swamp the whole comparison
    std::vector<std::vector<double>> curves(n, std::vector<double>(points)), slopes(n, std::vector<double>(points - 1));
    for (int i = 0; i < n; i++) {
        for (int k = 0; k < points; k++)
            curves[i][k] = results[i].first(-1.0 + 2.0 * k / (points - 1));
        for (int k = 0; k < points - 1; k++)
            slopes[i][k] = atan((curves[i][k + 1] - curves[i][k]) * (points - 1) / 2.0);
    }

    std::vector<std::vector<double>> curveDist(n, std::vector<double>(n, 0.0));
    for (int i = 0; i < n; i++) {
        for (int j = i + 1; j < n; j++) {
            double values = 0.0, slope = 0.0;
            for (int k = 0; k < points; k++) {
                double d = curves[i][k] - curves[j][k];
                values += d * d;
            }
            for (int k = 0; k < points - 1; k++) {
                double d = slopes[i][k] - slopes[j][k];
                slope += d * d;
            }
            curveDist[i][j] = curveDist[j][i] = values / points + slopeWeight * slope / (points - 1);
        }
    }

    // results are sorted by flatness, so index is flatness rank. penalising big rank jumps
    // keeps the path drifting from smooth to noisy instead of wandering back and forth
    std::vector<std::vector<double>> dist(n, std::vector<double>(n, 0.0));
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            double rank = double(i - j) / (n - 1);
            dist[i][j] = curveDist[i][j] + flatnessWeight * rank * rank;
        }
    }

    // greedy nearest neighbour from the first shape, saving the last shape for the end
    std::vector<int> path = {0};
    std::vector<bool> used(n, false);
    used[0] = used[n - 1] = true;
    for (int step = 1; step < n - 1; step++) {
        int best = -1;
        for (int j = 0; j < n; j++)
            if (!used[j] && (best < 0 || dist[path.back()][j] < dist[path.back()][best])) best = j;
        used[best] = true;
        path.push_back(best);
    }
    path.push_back(n - 1);

    // 2-opt: reverse any segment that shortens the path, endpoints stay fixed
    // ponytail: local optimum only, not the true shortest path. random restarts if it still jumps around
    auto twoOpt = [&]() {
        for (bool improved = true; improved;) {
            improved = false;
            for (int i = 1; i < n - 2; i++) {
                for (int j = i + 1; j < n - 1; j++) {
                    double delta = dist[path[i - 1]][path[j]] + dist[path[i]][path[j + 1]]
                                 - dist[path[i - 1]][path[i]] - dist[path[j]][path[j + 1]];
                    if (delta < -1e-12) {
                        std::reverse(path.begin() + i, path.begin() + j + 1);
                        improved = true;
                    }
                }
            }
        }
    };

    // outliers: shapes whose distance to both neighbours is far above the group's usual. worst first, pull each one out,
    // try every gap in the path and put it where it fits best. flatness counts here too: going on looks alone scattered
    // bright shapes (sine folds in the analog group) through the regular curves
    auto relocateOutliers = [&]() {
        std::vector<double> local(n, 0.0), costs; // local is indexed by shape
        for (int i = 1; i < n - 1; i++) {
            local[path[i]] = dist[path[i - 1]][path[i]] + dist[path[i]][path[i + 1]];
            costs.push_back(local[path[i]]);
        }

        // median and MAD, so a few huge jumps don't raise the bar for everything else
        auto median = [](std::vector<double> v) { std::sort(v.begin(), v.end()); return v[v.size() / 2]; };
        double mid = median(costs);
        for (double& c : costs) c = std::fabs(c - mid);
        double threshold = mid + outlierSigma * 1.4826 * median(costs);

        std::vector<int> outliers;
        for (int i = 1; i < n - 1; i++)
            if (local[path[i]] > threshold) outliers.push_back(path[i]);
        std::sort(outliers.begin(), outliers.end(), [&](int a, int b) { return local[a] > local[b]; });

        int moved = 0;
        for (int shape : outliers) {
            int at = int(std::find(path.begin(), path.end(), shape) - path.begin());
            double stayCost = dist[path[at - 1]][shape] + dist[shape][path[at + 1]] - dist[path[at - 1]][path[at + 1]];
            path.erase(path.begin() + at);

            // gap g sits between path[g - 1] and path[g], so the ends stay fixed
            int bestGap = at;
            double bestCost = stayCost;
            for (int g = 1; g < n - 1; g++) {
                double cost = dist[path[g - 1]][shape] + dist[shape][path[g]] - dist[path[g - 1]][path[g]];
                if (cost < bestCost - 1e-12) { bestCost = cost; bestGap = g; }
            }
            path.insert(path.begin() + bestGap, shape);
            if (bestGap != at) moved++;
        }
        return moved;
    };

    auto pathCost = [&](const std::vector<int>& order, const std::vector<std::vector<double>>& cost) {
        double total = 0.0;
        for (int i = 1; i < n; i++) total += cost[order[i - 1]][order[i]];
        return total;
    };

    std::vector<int> flatnessOrder(n);
    for (int i = 0; i < n; i++) flatnessOrder[i] = i;

    auto broken = [&](const char* why) {
        fprintf(stderr, "%s: similarity path is broken, %s\n", label, why);
        exit(1);
    };

    twoOpt();
    if (pathCost(path, dist) > pathCost(flatnessOrder, dist)) broken("worse than the flatness order");

    // each move strictly shortens the curve distance, so this settles
    double beforeRelocating = pathCost(path, curveDist);
    int relocated = 0;
    if (outlierSigma > 0.0)
        for (int moved; (moved = relocateOutliers()) > 0;) relocated += moved;
    if (pathCost(path, curveDist) > beforeRelocating + 1e-9) broken("relocation made it longer");

    // path must still hold every shape once with the same ends
    std::vector<int> check = path;
    std::sort(check.begin(), check.end());
    if (check != flatnessOrder || path.front() != 0 || path.back() != n - 1) broken("lost or moved a shape it shouldn't");

    std::vector<Result> ordered;
    for (int i : path) ordered.push_back(results[i]);

    // spearman correlation between path position and flatness rank, 1 = same as the flatness order
    if (log) {
        double rankDiffSq = 0.0;
        for (int i = 0; i < n; i++) rankDiffSq += double(i - path[i]) * (i - path[i]);
        double largestStep = 0.0;
        for (int i = 1; i < n; i++) largestStep = std::max(largestStep, curveDist[path[i - 1]][path[i]]);
        fprintf(stderr, "== %s ==\ntotal curve distance: flatness order %.3f, similarity path %.3f, rank correlation %.3f\n", label,
                pathCost(flatnessOrder, curveDist), pathCost(path, curveDist), 1.0 - 6.0 * rankDiffSq / (n * (double(n) * n - 1.0)));
        fprintf(stderr, "outliers moved %d, largest step %.4f\n", relocated, largestStep);
        for (int i = 0; i < n; i++) {
            auto& [shape, r] = ordered[i];
            fprintf(stderr, "%-20s step %.4f  flatness %.3e  oddness %.4f\n", shape.name,
                    i ? curveDist[path[i - 1]][path[i]] : 0.0, r.spectralFlatness, r.oddness);
        }
    }

    return ordered;
}

// RMS of a shape with the analysis sine through the plugin's input stage at a drive -- drive, tanh, bias and asym at 0 --
// and DC taken out like the plugin's highpass
double loudnessOf(const Shape& shape, double driveDb) {
    const int N = 4096;
    const double amplitude = std::pow(10.0, (analysisLevelDb + driveDb) / 20.0);
    double sum = 0.0, sumSquares = 0.0;
    for (int n = 0; n < N; n++) {
        double y = shape(std::tanh(amplitude * std::sin(2.0 * M_PI * n / N)));
        sum += y;
        sumSquares += y * y;
    }
    double mean = sum / N;
    return std::sqrt(std::max(sumSquares / N - mean * mean, 0.0));
}

struct Loudness {
    std::vector<std::array<double, driveSteps>> gains; // [shape][drive step]
    std::array<double, driveSteps> targets {};
};

// one drive step's rule, from every shape's RMS there: the target is the RMS 90% of shapes can reach without their gain
// passing maxLoudnessGain, and each shape's gain heads for it. returns the target
double loudnessStep(const std::vector<double>& rms, std::vector<double>& gains) {
    std::vector<double> reach;
    for (double r : rms) reach.push_back(maxLoudnessGain * r);
    std::sort(reach.begin(), reach.end());
    const double target = reach[reach.size() / 10];

    gains.resize(rms.size());
    for (size_t s = 0; s < rms.size(); s++)
        gains[s] = rms[s] > 1e-9 ? std::min(target / rms[s], maxLoudnessGain) : maxLoudnessGain;
    return target;
}

// loudnessStep at every drive step
Loudness loudnessTable() {
    Loudness loudness;
    loudness.gains.resize(shapes.size());
    for (int k = 0; k < driveSteps; k++) {
        std::vector<double> rms(shapes.size()), gains;
        for (size_t s = 0; s < shapes.size(); s++) rms[s] = loudnessOf(shapes[s], k * driveStepDb);
        loudness.targets[k] = loudnessStep(rms, gains);
        for (size_t s = 0; s < shapes.size(); s++) loudness.gains[s][k] = gains[s];
    }
    return loudness;
}

// WaveshapeOrder.h for the plugin: each group's shapes in the order just worked out, and every shape's loudness gains
void printOrderHeader(const std::vector<std::vector<Result>>& groups, const Loudness& loudness) {
    static const char* arrayNames[GroupCount] = { "analogOrder", "digitalOrder", "foldingOrder", "heavyOrder" };
    printf("#pragma once\n\n"
           "// generated by waveshape_features, don't edit. after changing Waveshapes.h, from the repo root:\n"
           "//   waveshape_features --header > dsp/Distortions/waveshape/WaveshapeOrder.h\n"
           "// each group runs smooth to bright. names sit next to the indices so a stale file gets caught\n\n"
           "#include \"Waveshapes.h\"\n\nnamespace waveshapes {\n");
    for (int g = 0; g < GroupCount; g++) {
        printf("    inline constexpr OrderEntry %s[] = {\n", arrayNames[g]);
        for (auto& result : groups[g]) {
            size_t index = 0;
            while (strcmp(shapes[index].name, result.first.name) != 0) index++;
            printf("        { %zu, \"%s\" },\n", index, result.first.name);
        }
        printf("    };\n\n");
    }
    printf("    inline constexpr GroupOrder groupOrders[GroupCount] = {\n");
    for (int g = 0; g < GroupCount; g++)
        printf("        { %s, %zu },\n", arrayNames[g], groups[g].size());
    printf("    };\n\n"
           "    // loudness gains on top of the peak normalisation, [shape index][drive step]. see loudnessGain() in Waveshapes.h\n"
           "    inline constexpr double loudnessGains[][driveSteps] = {\n");
    for (size_t s = 0; s < shapes.size(); s++) {
        printf("        {");
        for (int k = 0; k < driveSteps; k++) printf("%s%.7g", k ? ", " : " ", loudness.gains[s][k]); // 7 digits: far past audible, half the file
        printf(" }, // %s\n", shapes[s].name);
    }
    printf("    };\n}\n");
}

// the plugin plays WaveshapeOrder.h, so it has to agree with the table and morph cleanly through it
bool checkOrderHeader(const Loudness& loudness) {
#ifdef HAVE_ORDER_HEADER
    static CurveTable curveTable; // two 65k-point buffers, off the stack
    const char* stale = "WaveshapeOrder.h is out of date, regenerate it with --header";
    for (int g = 0; g < GroupCount; g++) {
        const auto& order = groupOrders[g];

        int expected = 0;
        for (auto& shape : shapes) expected += shape.group == g;
        if (order.count != expected) {
            fprintf(stderr, "%s: %s has %d shapes, the table has %d\n", stale, groupNames[g], order.count, expected);
            return false;
        }

        std::vector<int> seen(shapes.size(), 0);
        for (int i = 0; i < order.count; i++) {
            const auto& entry = order.entries[i];
            if (entry.index < 0 || entry.index >= (int)shapes.size() || strcmp(shapes[entry.index].name, entry.name) != 0
                || shapes[entry.index].group != g || seen[entry.index]++) {
                fprintf(stderr, "%s: entry %d of %s (%s)\n", stale, i, groupNames[g], entry.name);
                return false;
            }
        }

        // on a whole position the morph is exactly that shape
        for (int i = 0; i < order.count; i++) {
            const auto& shape = shapes[order.entries[i].index];
            for (int k = -1000; k <= 1000; k++) {
                double x = k / 1000.0;
                if (morph(order, i, x) != shape(x)) {
                    fprintf(stderr, "morph on %s doesn't match the shape at x = %f\n", shape.name, x);
                    return false;
                }
            }
        }

        // the plugin plays a CurveTable rather than morph: unsmoothed it has to land on the morph at its points,
        // and at the widest smoothing it has to stay finite and under maxPeak
        for (int i = 0; i < order.count; i++) {
            const char* name = shapes[order.entries[i].index].name;
            double position = std::min(i + 0.5, order.count - 1.0);

            curveTable.build(order, position, 0.0);
            for (int k = 0; k <= CurveTable::cells; k += 7) {
                double x = -CurveTable::span + k * CurveTable::cell;
                if (std::fabs(x) <= 1.0 && std::fabs(curveTable.read(x) - morph(order, position, x)) > 1e-9) {
                    fprintf(stderr, "curve table just after %s doesn't match the morph at x = %f\n", name, x);
                    return false;
                }
            }

            curveTable.build(order, position, maxSmoothWidth);
            for (int k = -1000; k <= 1000; k++) {
                double y = curveTable.read(k / 1000.0);
                if (!std::isfinite(y) || std::fabs(y) > maxPeak) {
                    fprintf(stderr, "smoothed curve table just after %s is %g at x = %f\n", name, y, k / 1000.0);
                    return false;
                }
            }
        }
    }

    // the asym skew runs on the driven signal, which can be huge: it has to stay finite (the plugin builds
    // with -ffast-math, which assumes it is) and still saturate the tanh the way an unbounded exp would. a strong
    // skew's negative side flattens out short of -1; a slight one's floor, -1 / k, is far enough out to reach it
    for (double asym : { 0.0, 0.01, 0.5, 1.0 }) {
        for (double v : { -1e6, -1e3, -40.0, -1.0, 0.0, 1.0, 40.0, 1e3, 1e6 }) {
            double y = std::tanh(skew(v, asym));
            if (!std::isfinite(skew(v, asym)) || !std::isfinite(y) || (v >= 40.0 && y != 1.0) || (asym >= 0.5 && v <= -40.0 && y <= -1.0)) {
                fprintf(stderr, "asym skew at asym %g, v = %g gives %g, tanh %g\n", asym, v, skew(v, asym), y);
                return false;
            }
        }
    }

    // smoothing has to be centred and has to actually round a corner off
    auto single = [](const char* name) {
        for (size_t i = 0; i < shapes.size(); i++)
            if (strcmp(shapes[i].name, name) == 0) return OrderEntry { (int)i, shapes[i].name };
        fprintf(stderr, "no shape called %s\n", name);
        exit(1);
    };
    const OrderEntry tanhEntry = single("tanhWaveShaper"), clipEntry = single("hardClip");

    // widths from a sliver of a cell, through a fractional box, to the widest
    for (double width : { 0.0002, 2.0 * 400.3 * CurveTable::cell, maxSmoothWidth }) {
        curveTable.build(GroupOrder { &tanhEntry, 1 }, 0.0, width);
        for (int k = 0; k <= 1000; k++) {
            double x = k / 1000.0;
            if (std::fabs(curveTable.read(x) + curveTable.read(-x)) > 1e-9) {
                fprintf(stderr, "smoothing isn't centred: tanhWaveShaper stops being odd at x = %f, width %g\n", x, width);
                return false;
            }
        }
    }

    const double corner = 1.0 / shapes[clipEntry.index].s; // hardClip hits full scale here
    curveTable.build(GroupOrder { &clipEntry, 1 }, 0.0, maxSmoothWidth);
    if (curveTable.read(corner) > morph(GroupOrder { &clipEntry, 1 }, 0.0, corner) - 0.01) {
        fprintf(stderr, "smoothing didn't round off hardClip's corner\n");
        return false;
    }

    // smoothing grows continuously from the first nudge of the knob: it already acts at 0.1%, the corner never
    // comes back up as the knob rises, and no step along the way is a jump
    curveTable.build(GroupOrder { &clipEntry, 1 }, 0.0, 0.0);
    double previous = curveTable.read(corner);
    for (int k = 1; k <= 1000; k++) {
        curveTable.build(GroupOrder { &clipEntry, 1 }, 0.0, smoothToWidth(k / 1000.0));
        double value = curveTable.read(corner);
        if (k == 1 ? value >= previous : value > previous + 1e-9) {
            fprintf(stderr, "smoothing %s at smooth %.1f%%: hardClip's corner went from %.12f to %.12f\n",
                    k == 1 ? "has a dead zone" : "goes back up", k / 10.0, previous, value);
            return false;
        }
        if (previous - value > 0.005) {
            fprintf(stderr, "smoothing jumps at smooth %.1f%%: hardClip's corner dropped %g\n", k / 10.0, previous - value);
            return false;
        }
        previous = value;
    }

    // the loudness gains have to be current, and between drive steps a shape may drift at most 1 dB off the level it's
    // aiming for. shapes held at maxLoudnessGain on either side aren't aiming for it, so they're left out
    const char* staleLoudness = "WaveshapeOrder.h's loudness gains are out of date, regenerate it with --header";
    if (std::size(loudnessGains) != shapes.size()) {
        fprintf(stderr, "%s: %zu rows for %zu shapes\n", staleLoudness, std::size(loudnessGains), shapes.size());
        return false;
    }
    for (size_t s = 0; s < shapes.size(); s++)
        for (int k = 0; k < driveSteps; k++)
            if (std::fabs(loudnessGains[s][k] - loudness.gains[s][k]) > 1e-6 * loudness.gains[s][k]) { // printed to 7 digits
                fprintf(stderr, "%s: %s at %g dB drive\n", staleLoudness, shapes[s].name, k * driveStepDb);
                return false;
            }

    double worstDrift = 0.0, worstDrive = 0.0;
    const char* worstName = "";
    for (size_t s = 0; s < shapes.size(); s++) {
        const OrderEntry entry { (int)s, shapes[s].name };
        for (int k = 0; k + 1 < driveSteps; k++) {
            if (loudness.gains[s][k] >= maxLoudnessGain || loudness.gains[s][k + 1] >= maxLoudnessGain) continue;
            double driveDb = (k + 0.5) * driveStepDb;
            double level = loudnessOf(shapes[s], driveDb) * loudnessGain(GroupOrder { &entry, 1 }, 0.0, driveDb, loudnessGains);
            double drift = std::fabs(20.0 * std::log10(level / std::sqrt(loudness.targets[k] * loudness.targets[k + 1])));
            if (drift > worstDrift) { worstDrift = drift; worstName = shapes[s].name; worstDrive = driveDb; }
        }
    }
    fprintf(stderr, "loudness: worst drift between drive steps %.2f dB (%s at %g dB drive)\n", worstDrift, worstName, worstDrive);
    if (worstDrift > 1.0) {
        fprintf(stderr, "loudness drifts more than 1 dB between drive steps\n");
        return false;
    }

    // what all this is for: the level jump between neighbouring shapes in each group's order
    for (double driveDb : { 0.0, 12.0, 24.0, 36.0 }) {
        for (int g = 0; g < GroupCount; g++) {
            const auto& order = groupOrders[g];
            std::vector<double> steps;
            double previousLevel = 0.0;
            int capped = 0;
            for (int i = 0; i < order.count; i++) {
                const int index = order.entries[i].index;
                double gain = loudnessGain(order, i, driveDb, loudnessGains);
                double level = loudnessOf(shapes[index], driveDb) * gain;
                capped += gain >= maxLoudnessGain;
                if (i) steps.push_back(std::fabs(20.0 * std::log10(level / previousLevel)));
                previousLevel = level;
            }
            std::sort(steps.begin(), steps.end());
            fprintf(stderr, "loudness jumps at %2g dB drive  %-28s median %4.1f dB  90%% %4.1f dB  worst %4.1f dB  (%d held at max gain)\n",
                    driveDb, groupNames[g], steps[steps.size() / 2], steps[steps.size() * 9 / 10], steps.back(), capped);
        }
    }
    return true;
#else
    fprintf(stderr, "no WaveshapeOrder.h yet, generate it with --header\n");
    return true;
#endif
}

// the plugin's XY pad plays WaveshapeMap.h: every shape has to be on it once and inside the pad's disc, a dot has to give exactly its shape,
// and blending between dots has to be a proper blend that never jumps
bool checkMapHeader() {
#ifdef HAVE_MAP_HEADER
    const char* stale = "WaveshapeMap.h is out of date, regenerate it with analysis/umap_shapes.py --header (after harmonic_features)";
    const int count = (int)std::size(mapPoints);
    if (count != (int)shapes.size()) {
        fprintf(stderr, "%s: %d points for %zu shapes\n", stale, count, shapes.size());
        return false;
    }
    std::vector<int> seen(shapes.size(), 0);
    for (auto& point : mapPoints) {
        if (point.index < 0 || point.index >= (int)shapes.size() || strcmp(shapes[point.index].name, point.name) != 0
            || seen[point.index]++ || std::hypot(point.x - 0.5, point.y - 0.5) > 0.5 + 1e-6) { // the pad's disc
            fprintf(stderr, "%s: %s\n", stale, point.name);
            return false;
        }
    }

    for (auto& point : mapPoints) {
        const Mix mix = mixAt(mapPoints, count, point.x, point.y);
        if (mix.count != 1 || mix.index[0] != point.index || mix.weight[0] != 1.0) {
            fprintf(stderr, "the pad on %s's dot isn't just %s\n", point.name, point.name);
            return false;
        }
    }

    std::mt19937 rng(11);
    std::uniform_real_distribution<double> uniform(0.0, 1.0);
    const double probes[] = { -1.0, -0.5, 0.0, 0.3, 0.9 };

    for (int n = 0; n < 20000; n++) {
        const Mix mix = mixAt(mapPoints, count, uniform(rng), uniform(rng));
        double total = 0.0;
        for (int i = 0; i < mix.count; i++) {
            if (!(mix.weight[i] >= 0.0)) {
                fprintf(stderr, "a pad weight is %g\n", mix.weight[i]);
                return false;
            }
            total += mix.weight[i];
        }
        if (mix.count == 0 || std::fabs(total - 1.0) > 1e-9) {
            fprintf(stderr, "pad weights sum to %.12f over %d shapes\n", total, mix.count);
            return false;
        }
    }

    // where a shape joins the nearest few is where a careless blend would jump. walk from a random point towards the
    // shape just outside its nearest few, find where it joins by bisection, and compare the curve either side of that
    double worstJump = 0.0;
    for (int n = 0; n < 2000; n++) {
        const double startX = uniform(rng), startY = uniform(rng);
        std::vector<std::pair<double, int>> byDistance;
        for (int p = 0; p < count; p++) byDistance.push_back({ std::hypot(mapPoints[p].x - startX, mapPoints[p].y - startY), p });
        std::sort(byDistance.begin(), byDistance.end());
        const MapPoint& joining = mapPoints[byDistance[mapNeighbours].second];

        auto at = [&](double t) { return mixAt(mapPoints, count, startX + t * (joining.x - startX), startY + t * (joining.y - startY)); };
        auto holds = [&](const Mix& mix) {
            for (int i = 0; i < mix.count; i++) if (mix.index[i] == joining.index) return true;
            return false;
        };

        double outside = 0.0, inside = 1.0;
        if (holds(at(outside)) || !holds(at(inside))) continue;
        for (int step = 0; step < 60; step++) {
            const double middle = 0.5 * (outside + inside);
            (holds(at(middle)) ? inside : outside) = middle;
        }
        const Mix before = at(outside), after = at(inside);
        for (double x : probes) worstJump = std::max(worstJump, std::fabs(mixCurve(before, x) - mixCurve(after, x)));
    }
    fprintf(stderr, "pad: worst jump where a shape joins the blend %.2g\n", worstJump);
    if (worstJump > 1e-6) {
        fprintf(stderr, "blending across the pad jumps where a shape joins the nearest few\n");
        return false;
    }

    // re-levelling is 1 on a dot and between 1 and maxRelevel anywhere else
    for (auto& point : mapPoints) {
        if (mixRelevel(mixAt(mapPoints, count, point.x, point.y), 0.0, loudnessGains) != 1.0) {
            fprintf(stderr, "re-levelling isn't 1 on %s's dot\n", point.name);
            return false;
        }
    }

    // and the report: how far a re-levelled blend still sits below the shapes in it, measured with a longer sine than the plugin uses
    auto blendLevels = [](const Mix& mix, double driveDb, double& blend, double& expected) {
        const int N = 1024;
        const double amplitude = std::pow(10.0, (analysisLevelDb + driveDb) / 20.0);
        std::vector<double> sum(N, 0.0);
        expected = 0.0;
        for (int i = 0; i < mix.count; i++) {
            const Mix one { 1, { mix.index[i] }, { 1.0 } };
            const double gain = mixLoudness(one, driveDb, loudnessGains);
            std::vector<double> y(N);
            double mean = 0.0, power = 0.0;
            for (int n = 0; n < N; n++) { y[n] = shapes[mix.index[i]](std::tanh(amplitude * std::sin(2.0 * M_PI * n / N))) * gain; mean += y[n] / N; }
            for (int n = 0; n < N; n++) { power += (y[n] - mean) * (y[n] - mean); sum[n] += mix.weight[i] * y[n]; }
            expected += mix.weight[i] * std::sqrt(power / N);
        }
        double mean = 0.0, power = 0.0;
        for (double v : sum) mean += v / N;
        for (double v : sum) power += (v - mean) * (v - mean);
        blend = std::sqrt(power / N);
    };

    for (double driveDb : { 0.0, 24.0 }) {
        const int side = 40;
        std::vector<double> below;
        for (int gy = 0; gy < side; gy++) {
            for (int gx = 0; gx < side; gx++) {
                const double px = (gx + 0.5) / side, py = (gy + 0.5) / side;
                const Mix mix = mixAt(mapPoints, count, px, py);
                const double relevel = mixRelevel(mix, driveDb, loudnessGains);
                if (!(relevel >= 1.0 && relevel <= maxRelevel)) {
                    fprintf(stderr, "re-levelling at (%f, %f) is %g\n", px, py, relevel);
                    return false;
                }
                double blend, expected;
                blendLevels(mix, driveDb, blend, expected);
                below.push_back(20.0 * std::log10(std::max(blend * relevel, 1e-12) / std::max(expected, 1e-12)));
            }
        }
        std::sort(below.begin(), below.end());
        fprintf(stderr, "pad at %2g dB drive: re-levelled blends against their shapes: median %.1f dB, 10%% worst %.1f dB, 1%% worst %.1f dB, worst %.1f dB\n",
                driveDb, below[below.size() / 2], below[below.size() / 10], below[below.size() / 100], below.front());
    }
    return true;
#else
    fprintf(stderr, "no WaveshapeMap.h yet, generate it with analysis/umap_shapes.py --header (after harmonic_features)\n");
    return true;
#endif
}

int main(int argc, char** argv) {
    const int totalSamples = (int)sampleRate * seconds;
    const int harmonics = 512;

    std::vector<double> signal(totalSamples);
    std::vector<double> harmonicMags(harmonics);
    std::vector<Result> results;

    // every normalised shape must stay finite and under maxPeak over the whole input range, on a grid 200x finer
    // than the one its peak was found on
    for (auto& shape : shapes) {
        for (int i = -100000; i <= 100000; i++) {
            double x = i / 100000.0;
            double y = shape(x);
            if (!std::isfinite(y) || std::fabs(y) > maxPeak) {
                fprintf(stderr, "%s is %s at x = %f\n", shape.name, std::isfinite(y) ? "past maxPeak" : "not finite", x);
                return 1;
            }
        }
    }

    std::vector<double> input(totalSamples);
    for (int i = 0; i < totalSamples; i++)
        input[i] = std::pow(10.0, analysisLevelDb / 20.0) * sinewave((float)i, baseFreq);

    for (auto& shape : shapes) {
        // time only the shaping. best of a few runs so scheduler hiccups don't count against a shape
        // ponytail: one sine at full scale, shapes with input-dependent branches may be slower on other material
        double bestNs = 1e300;
        for (int run = 0; run < 5; run++) {
            auto start = std::chrono::steady_clock::now();
            for (int i = 0; i < totalSamples; i++)
                signal[i] = shape(input[i]);
            bestNs = std::min(bestNs, std::chrono::duration<double, std::nano>(std::chrono::steady_clock::now() - start).count());
        }

        HarmonicResults result = harmonicAnalyse(signal, harmonicMags.data(), totalSamples, harmonics);
        result.nsPerSample = bestNs / totalSamples;
        results.push_back({shape, result});
    }

    if (argc > 1 && std::string(argv[1]) == "--speed") {
        bool slowBuild = false;
#if !defined(__OPTIMIZE__) || defined(__SANITIZE_ADDRESS__)
        slowBuild = true;
#endif
#if defined(__has_feature)
#if __has_feature(address_sanitizer)
        slowBuild = true; // clang doesn't define __SANITIZE_ADDRESS__
#endif
#endif
        if (slowBuild)
            fprintf(stderr, "warning: unoptimised or sanitiser build, these timings won't match the plugin\n");
        std::sort(results.begin(), results.end(), [](auto& a, auto& b) {
            return a.second.nsPerSample > b.second.nsPerSample;
        });

        // x median points out the outliers. realtime instances = how many copies fit in one sample period at this rate
        double median = results[results.size() / 2].second.nsPerSample;
        printf("%-22s %-28s %10s %9s %18s\n", "shape", "group", "ns/sample", "x median", "realtime instances");
        for (auto& [shape, r] : results)
            printf("%-22s %-28s %10.2f %9.1f %18.0f\n", shape.name, groupNames[shape.group], r.nsPerSample,
                   r.nsPerSample / median, 1e9 / sampleRate / r.nsPerSample);
        return 0;
    }

    const std::string mode = argc > 1 ? argv[1] : "";
    const bool tuiMode = mode == "--tui", headerMode = mode == "--header";

    std::vector<std::vector<Result>> groups(GroupCount);
    for (auto& result : results) groups[result.first.group].push_back(result);
    for (int g = 0; g < GroupCount; g++)
        groups[g] = similarityOrder(groups[g], groupNames[g], !tuiMode && !headerMode);

    if (headerMode) {
        printOrderHeader(groups, loudnessTable());
        return 0;
    }

    if (tuiMode)
        return tui(groups);

    if (!checkOrderHeader(loudnessTable()) || !checkMapHeader())
        return 1;

    // stdout: just the ordered names, group by group
    for (auto& group : groups)
        for (auto& result : group)
            std::cout << result.first.name << "\n";
}
