name: Hamburger Build

env:
  PLUG: Hamburger
  NOSPACE: Hamburger

on:
  push:
    paths:
      - '*'
  pull_request:
    paths:
      - '*'
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    #- name: (linux) install juce dependencies
    #  id: juce_dependencies
    #  run: |
    #    pamac update
    #    pamac install --no-confirm gcc alsa-lib jack2 ladspa libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev

    - name: create directories
      id: create_dirs
      run: |
        mkdir "./gh_artifacts/"
        mkdir "./gh_artifacts/Manual Install"

    - name: (unix linux) configure
      id: configure
      run: |
        cmake -B "build_linux" -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release

    - name: build
      id: build
      run: |
        cmake --build "build_linux" --config Release --target ${{env.NOSPACE}}_VST3 -j
        cmake --build "build_linux" --config Release --target ${{env.NOSPACE}}_CLAP -j

    - name: (linux) package
      id: package_linux
      run: |
        pwd
        mv "./build_linux/${{env.PLUG}}.vst3" "./gh_artifacts/Manual Install/${{env.PLUG}}.vst3"
        mv "./build_linux/${{env.PLUG}}.clap" "./gh_artifacts/Manual Install/${{env.PLUG}}.clap"

    - uses: actions/upload-artifact@v3
      with:
        name: "${{env.PLUG}} Linux (x86_64)"
        path: "./gh_artifacts"
